add protobuf support
moleculer-ruby/moleculer pull request #74
Opened 2019-08-27 11:12 UTC by fugufish

2019-08-27 13:55 UTC, betacar submitted a review, later dismissed
This is awesome! 💯

2019-08-27 16:47 UTC, reecebisel requested changes

2019-08-27 16:47 UTC, reecebisel commented on lib/moleculer/packets.rb
> +      Discover.packet_name.downcase.to_sym   => Discover,
We should define a new method for this. Rather than downcasing and to symbol packet name. We could call this `packet_symbol`, `packet_lookup`, `packet_token` or something along those lines.

2019-08-27 16:47 UTC, reecebisel commented on lib/moleculer/transporters/redis.rb
> +              channel: channel,
These are spaced wrong, or was this on purpose?

2019-08-27 16:47 UTC, reecebisel commented on spec/moleculer/serializers/json_spec.rb
> +  include_examples "serializer"
It's good to see this again.

2019-08-27 16:47 UTC, reecebisel commented on Gemfile.lock
> +    activesupport (5.2.3)
will this cause issues with older rails versions?

2019-08-27 16:47 UTC, reecebisel commented on lib/moleculer/serializers/protobuf/packets/packets.pb.rb
> +
We should remove the extra spaces around these. It is inconsistent with the rest of the file, and that's silly.

2019-08-27 17:50 UTC, fugufish commented on Gemfile.lock
> +    activesupport (5.2.3)
eh.. it shouldn't depend on AS, let me look into that.

2019-08-27 17:53 UTC, fugufish commented on lib/moleculer/serializers/protobuf/packets/packets.pb.rb
> +
this file is autogenerated, while I agree it's silly because of the generation method we would have to do it every time, which is also silly. I'm not opposed to running rubocop auto fixer on it and see what that does though.

2019-08-27 18:00 UTC, fugufish commented on Gemfile.lock
> +    activesupport (5.2.3)
it shouldn't from what I can see because of how the requirements are set. but I added it explicitly as well.

2019-08-29 17:39 UTC, reecebisel approved these changes

2019-08-29 17:41 UTC, merged